
project_id = "hjiublwdlvzmowxldstd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "http://localhost:54324"
redirect_urls = ["https://localhost:3000/**"]

additional_redirect_urls = ["https://localhost:3000/**"]
site_url = "http://localhost:3000"
jwt_expiry = 3600
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"

[inbucket]
enabled = true
port = 54325

[functions.create-payment]
verify_jwt = true

[functions.payment-callback]
verify_jwt = false
